2020-12-15 22:53:36,607.607 DEBUG    [main.py:30] Start
2020-12-15 22:53:36,607.607 DEBUG    [main.py:31] Entered arguments
2020-12-15 22:53:36,608.608 INFO     [main.py:42] Starting the server at: 
2020-12-15 22:53:36,608.608 INFO     [main.py:43] 	IP Address: 127.0.0.1
2020-12-15 22:53:36,608.608 INFO     [main.py:44] 	Port: 5000
2020-12-15 22:53:36,612.612 INFO     [routes.py:21] JSON received: {'signal': '27'}
2020-12-15 22:53:50,914.914 DEBUG    [main.py:30] Start
2020-12-15 22:53:50,914.914 DEBUG    [main.py:31] Entered arguments
2020-12-15 22:53:50,915.915 INFO     [main.py:42] Starting the server at: 
2020-12-15 22:53:50,915.915 INFO     [main.py:43] 	IP Address: 127.0.0.1
2020-12-15 22:53:50,915.915 INFO     [main.py:44] 	Port: 5000
2020-12-15 22:53:50,919.919 INFO     [routes.py:21] JSON received: {'signal': '27'}
2020-12-15 22:53:50,922.922 INFO     [routes.py:21] JSON received: {'signal': '10'}
2020-12-15 22:54:26,767.767 DEBUG    [main.py:30] Start
2020-12-15 22:54:26,767.767 DEBUG    [main.py:31] Entered arguments
2020-12-15 22:54:26,768.768 INFO     [main.py:42] Starting the server at: 
2020-12-15 22:54:26,768.768 INFO     [main.py:43] 	IP Address: 127.0.0.1
2020-12-15 22:54:26,769.769 INFO     [main.py:44] 	Port: 5000
2020-12-15 22:54:26,772.772 INFO     [routes.py:21] JSON received: {'signal': '27'}
2020-12-15 22:54:26,775.775 INFO     [routes.py:21] JSON received: {'signal': '10'}
2020-12-15 22:56:41,622.622 DEBUG    [main.py:30] Start
2020-12-15 22:56:41,622.622 DEBUG    [main.py:31] Entered arguments
2020-12-15 22:56:46,199.199 DEBUG    [main.py:30] Start
2020-12-15 22:56:46,200.200 DEBUG    [main.py:31] Entered arguments
2020-12-15 22:56:46,201.201 INFO     [_internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-12-15 22:57:14,615.615 INFO     [routes.py:21] JSON received: {'signal': '10'}
2020-12-15 22:57:14,616.616 INFO     [_internal.py:113] 127.0.0.1 - - [15/Dec/2020 22:57:14] "[37mPOST / HTTP/1.1[0m" 200 -
2020-12-15 22:57:18,329.329 INFO     [routes.py:21] JSON received: {'signal': '11'}
2020-12-15 22:57:18,330.330 INFO     [_internal.py:113] 127.0.0.1 - - [15/Dec/2020 22:57:18] "[37mPOST / HTTP/1.1[0m" 200 -
2020-12-15 22:57:21,667.667 INFO     [routes.py:21] JSON received: {'signal': '23'}
2020-12-15 22:57:21,667.667 INFO     [_internal.py:113] 127.0.0.1 - - [15/Dec/2020 22:57:21] "[37mPOST / HTTP/1.1[0m" 200 -
2020-12-15 22:57:24,428.428 INFO     [routes.py:21] JSON received: {'signal': '27'}
2020-12-15 22:57:24,428.428 INFO     [_internal.py:113] 127.0.0.1 - - [15/Dec/2020 22:57:24] "[37mPOST / HTTP/1.1[0m" 200 -
2020-12-15 22:57:29,133.133 INFO     [routes.py:21] JSON received: {'singal': '27'}
2020-12-15 22:57:29,134.134 ERROR    [routes.py:36] Received key input error 'signal'
Traceback (most recent call last):
  File "/home/mirkwood/Workspace/git/signal_interpreter_groupwork/signal_interpreter_server/src_server/routes.py", line 30, in interpret_signal
    signal_name = signal_ps.get_signal_by_id(data["signal"])
KeyError: 'signal'
2020-12-15 22:57:29,134.134 ERROR    [app.py:1891] Exception on / [POST]
Traceback (most recent call last):
  File "/home/mirkwood/Workspace/git/signal_interpreter_groupwork/signal_interpreter_server/src_server/routes.py", line 30, in interpret_signal
    signal_name = signal_ps.get_signal_by_id(data["signal"])
KeyError: 'signal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mirkwood/Workspace/git/signal_interpreter_groupwork/.venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mirkwood/Workspace/git/signal_interpreter_groupwork/.venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mirkwood/Workspace/git/signal_interpreter_groupwork/.venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mirkwood/Workspace/git/signal_interpreter_groupwork/.venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mirkwood/Workspace/git/signal_interpreter_groupwork/.venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mirkwood/Workspace/git/signal_interpreter_groupwork/.venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mirkwood/Workspace/git/signal_interpreter_groupwork/signal_interpreter_server/src_server/routes.py", line 37, in interpret_signal
    abort(400, description=f"{data['signal']} did not return correct values. Key error!")
KeyError: 'signal'
2020-12-15 22:57:29,136.136 INFO     [_internal.py:113] 127.0.0.1 - - [15/Dec/2020 22:57:29] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2020-12-15 22:58:48,802.802 INFO     [main.py:42] Starting the server at: 
2020-12-15 22:58:48,803.803 INFO     [main.py:43] 	IP Address: 127.0.0.1
2020-12-15 22:58:48,803.803 INFO     [main.py:44] 	Port: 5000
